Feature/table
PeaksoftFrontend/HealthCheck-js2 pull request #18
Opened 2024-09-27 23:31 UTC by AziretTursunbekov

2024-09-28 03:18 UTC, Nooruzbekck commented on src/components/Table.jsx
>      <StyledTable {...getTableProps()}>
Сразу эле useTable дан деструктуризация кылсан болот

2024-10-17 05:55 UTC, AziatAbd requested changes

2024-10-17 05:55 UTC, AziatAbd commented on src/utils/constants/table.js
> +const [data, setData] = useState(
Хуки вызываются только в компонентах. Удалите

2024-10-17 05:55 UTC, AziatAbd commented on src/components/Table.jsx
> +export const Table = ({ columns, data, isVariant }) => {
зачем isVariant? Уберите

2024-10-17 05:55 UTC, AziatAbd commented on src/utils/constants/table.js
если в файле есть хоть один JSX то это уже не JS файл, а JSX. Измените на JSX

2024-10-17 05:55 UTC, AziatAbd commented on src/utils/constants/table.js
> +export const TABLE = useMemo(
useMemo удаляем

2024-10-17 05:55 UTC, AziatAbd commented on src/components/Table.jsx
![image](https://github.com/user-attachments/assets/7cff4e08-83fb-4c85-8d61-d344619c94c5)
дайте width 100% чтобы занимал всю страницу

2024-10-17 05:55 UTC, AziatAbd commented on src/components/Table.jsx
thead шрифты должны быть жирными

2024-10-21 03:21 UTC, AziatAbd approved these changes

2024-10-23 06:54 UTC, merged